services:
  converter:
    image: node:current-alpine
    user: "${UID}:${GID}"
    volumes:
      - ../:/srv/app/
    working_dir: /srv/app/example/converter
    entrypoint: npm run start:dev
    environment:
      PORT: 80
      NODE_OPTIONS: --inspect-port=0.0.0.0
    ports:
      - "8082:80"
      - "9229"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017
  mongo-import:
    image: mongo
    command: |
      mongoimport
        --host mongo 
        --db nestjs_mongoose 
        --collection cats
        --username root --password root
        --authenticationDatabase admin
        --file /cats.csv
        --type csv --headerline
    volumes:
      - ./cats.csv:/cats.csv
    depends_on:
      - mongo
  ui:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
